version: '2.1'

networks:
  keycloak-network:

volumes:
    keycloak-postgres-data:
    keycloak-nginx-letsencrypt-ssl:

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    networks:
      - keycloak-network
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=$KEYCLOAK_PASSWORD
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
  keycloak:
    image: "jboss/keycloak-postgres:${KEYCLOAK_VERSION}"
    container_name: keycloak
    links:
      - postgres
    networks:
      - keycloak-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=$KEYCLOAK_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD
      # JBoss is using legacy linking environment variables
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - KEYCLOAK_VERSION
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
  nginx:
    image: ernsheong/keycloak-nginx-lets-encrypt
    container_name: nginx
    networks:
      - keycloak-network
    depends_on:
      - keycloak
    volumes:
      - keycloak-nginx-letsencrypt-ssl:/etc/letsencrypt
    environment:
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_DOMAIN
      - LE_EMAIL
      - LE_OPTIONS
      - LE_RENEW_OPTIONS
      - LE_RENEW_CRON_COMMAND
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
